##################################################################################
##################################################################################
# Automation Title:                                             Updated 24.02.2025
#   Tautulli Kill Streams - All Streams for a Single User
#
##################################################################################
##################################################################################
# How to Use:
# 1) Copy this YAML snippet into your Home Assistant automations.
#    - If using "automations.yaml", paste it there.
#    - If using the UI-based editor, switch to YAML mode and paste it.
# 2) Adjust the 'excluded_users' list under 'variables:' to specify any users who
#    can have multiple concurrent sessions without termination.
# 3) Confirm that 'sensor.tautulli_stream_count' is the correct aggregator sensor
#    in your setup. It must have 'sessions' containing 'user', 'session_id', etc.
# 4) Reload or restart automations (Developer Tools → YAML → "Reload Automations")
#    or from the UI, so that this new automation is active.
#
# What This Automation Does:
# - Whenever 'sensor.tautulli_stream_count' changes, it checks if any session 
#   belongs to the specified "CHANGE_ME" user.
# - If so, it calls the Tautulli kill_user_stream service to terminate all 
#   streams for that user.
##################################################################################

alias: Tautulli Kill Streams - Limit Fixed User - Kill All
description: >
  Terminates all Plex streams for "CHANGE_ME" whenever sensor.tautulli_stream_count changes.

##################################################################################
# Trigger:
#   Observes state changes in sensor.tautulli_stream_count.
##################################################################################
trigger:
  - platform: state
    entity_id: sensor.tautulli_stream_count

##################################################################################
# Condition:
#   Checks if "john_smith" appears in the sensor's 'sessions' attribute, 
#   using a namespace to properly detect matches.
##################################################################################
condition:
  - condition: template
    value_template: >-
      {% set sessions = state_attr('sensor.tautulli_stream_count','sessions') %}
      {% if sessions is none or sessions|length == 0 %}
        false
      {% else %}
        {% set ns = namespace(found=false) %}
        {% for s in sessions %}
          {% if s.username is defined and s.username|lower|trim == 'CHANGE_ME' %}
            {% set ns.found = true %}
          {% endif %}
        {% endfor %}
        {{ ns.found }}
      {% endif %}

##################################################################################
# Action:
#   Invokes 'kill_user_stream' to forcibly end all streams for "john_smith".
##################################################################################
action:
  - service: tautulli_active_streams.kill_user_stream
    data:
      user: "CHANGE_ME"
      message: "Stream has been stopped by Admin. Contact for Support"
mode: single
##################################################################################
#  
#      please give our repo a like :)
#    
##################################################################################
